/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loren_inventory;

import Connection.connect;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author student.admin
 */
public class Product extends javax.swing.JFrame {

    java.sql.Connection con;
    PreparedStatement pst;

    public Product() {
        initComponents();
        this.setLocationRelativeTo(null); // center form on the screen
        String url = "jdbc:mysql://localhost/super mall";
        String user = "root";
        String pass = "";
        try {
            con = DriverManager.getConnection(url, user, pass);
        } catch (Exception ex) {
            System.out.println("Error : " + ex.getMessage());
        }
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jProd = new javax.swing.JTextField();
        jadd = new javax.swing.JButton();
        jdel = new javax.swing.JButton();
        jupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDescription = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jcost = new javax.swing.JTextField();
        jquant = new javax.swing.JTextField();
        jbarcode = new javax.swing.JTextField();
        jstat = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jProd1 = new javax.swing.JTextField();
        jadd1 = new javax.swing.JButton();
        jadd2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("/-\\ STR0 ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Star Merchandise Inventory System");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("|");

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Product");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("POS");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Exit");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cashier ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)))
                .addGap(38, 38, 38))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setText("Product");

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 8)); // NOI18N
        jLabel11.setText("_______________________________________________________________________________________________________________");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Product : ");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Description :");

        jadd.setText("Add");
        jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddActionPerformed(evt);
            }
        });

        jdel.setText("Delete");
        jdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdelActionPerformed(evt);
            }
        });

        jupdate.setText("Update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product_Id", "Product", "Description", "Cost Price", "Quantity", "Barcode ", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jDescription);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Cost Price :");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Quantity :");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Barcode :");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Status :");

        jstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Off" }));
        jstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstatActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Product Id : ");

        jadd1.setText("View Product Table");
        jadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadd1ActionPerformed(evt);
            }
        });

        jadd2.setText("Refresh ");
        jadd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadd2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 378, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProd, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jadd)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jdel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jupdate))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jstat, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbarcode, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jquant, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcost, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jadd1)
                .addGap(18, 18, 18)
                .addComponent(jadd2)
                .addGap(360, 360, 360))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jProd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jcost, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jquant, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jstat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jadd)
                            .addComponent(jdel)
                            .addComponent(jupdate)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jadd1)
                    .addComponent(jadd2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void table_update() {
        String sql = "SELECT * FROM products";
        int c;
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
                Vector v2 = new Vector();

                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("Product_Id "));
                    v2.add(rs.getString("Product"));
                    v2.add(rs.getString("Description"));
                    v2.add(rs.getString("Cost Price"));
                    v2.add(rs.getString("Quantity"));
                    v2.add(rs.getString("Barcode"));
                    v2.add(rs.getString("Status"));

                }

                model.addRow(v2);

            }
        } catch (Exception ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }
    private void jstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jstatActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Product p = new Product();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        POS po = new POS();
        po.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddActionPerformed
        String prod = jProd.getText();
        String prod1 = jProd1.getText();
        String descript = jDescription.getText();
        String cost = jcost.getText();
        String quant = jquant.getText();
        String bar = jbarcode.getText();
        String status = jstat.getSelectedItem().toString();

        if (prod.equals("")) {
            JOptionPane.showMessageDialog(null, "Add A Product Category");
        } else if (checkProdId(prod1)) {
            JOptionPane.showMessageDialog(null, "This Product Id Already Exist");
        } else if (checkBar(bar)) {
            JOptionPane.showMessageDialog(null, "This Barcode Already Exist");
        } else if (descript.equals("")) {
            JOptionPane.showMessageDialog(null, "Add A Product Description");
        } else if (cost.equals("")) {
            JOptionPane.showMessageDialog(null, "Add A Product Cost");
        } else if (quant.equals("")) {
            JOptionPane.showMessageDialog(null, "Add A Product Quantity");
        } else if (bar.equals("")) {
            JOptionPane.showMessageDialog(null, "Add A Product Barcode");
        } else if (status.equals("Active")) {
            JOptionPane.showMessageDialog(null, "Reminder: You are adding an Active Category");

            PreparedStatement ps;
            String query = "INSERT INTO `products`(`Product_Id`,`Product`,`Description`,`Cost Price`, `Quantity`,`Barcode`, `Status`) VALUES (?,?,?,?,?,?,?)";
            try {
                ps = connect.getConnection().prepareStatement(query);

                ps.setString(1, prod1);
                ps.setString(2, prod);
                ps.setString(3, descript);
                ps.setString(4, cost);
                ps.setString(5, quant);
                ps.setString(6, bar);
                ps.setString(7, status);

                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Successfully Added");
                    table_update();
                }

            } catch (SQLException ex) {
                System.out.println("Error : " + ex.getMessage());
            }
        } else if (!status.equals("Active")) {
            JOptionPane.showMessageDialog(null, "Reminder: You are adding a DeActive Category");
            PreparedStatement ps;
            String query = "INSERT INTO `products`(`Product_Id`,`Product`,`Description`,`Cost Price`, `Quantity`,`Barcode`, `Status`) VALUES (?,?,?,?,?,?,?)";

            try {
                ps = connect.getConnection().prepareStatement(query);

                ps.setString(1, prod1);
                ps.setString(2, prod);
                ps.setString(3, descript);
                ps.setString(4, cost);
                ps.setString(5, quant);
                ps.setString(6, bar);
                ps.setString(7, status);
                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Successfully Added");
                    table_update();
                }

            } catch (SQLException ex) {
                System.out.println("Error : " + ex.getMessage());
            }
        } else {
            PreparedStatement ps;
            String query = "INSERT INTO `products`(`Product_Id`,`Product`,`Description`,`Cost Price`, `Quantity`,`Barcode`, `Status`) VALUES (?,?,?,?,?,?,?)";
            try {
                ps = connect.getConnection().prepareStatement(query);

                ps.setString(1, prod1);
                ps.setString(2, prod);
                ps.setString(3, descript);
                ps.setString(4, cost);
                ps.setString(5, quant);
                ps.setString(6, bar);
                ps.setString(7, status);

                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "New Product Added");
                    table_update();
                }

            } catch (SQLException ex) {
                System.out.println("Error : " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jaddActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
        DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();

        int selectIndex = jTable1.getSelectedRow();

        String prod = jProd.getText();
        String prod1 = jProd1.getText();
        String descript = jDescription.getText();
        String cost = jcost.getText();
        String quant = jquant.getText();
        String bar = jbarcode.getText();
        String status = jstat.getSelectedItem().toString();

        try {
            int d = Integer.parseInt(model2.getValueAt(selectIndex, 0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/super mall", "root", "");
            pst = con.prepareStatement("update products set  Product=?, Description=? , Cost Price =? , Quantity =? ,Barcode =? , Status=? where Product_Id=? ");
            pst.setString(1, prod);
            pst.setString(2, descript);
            pst.setString(3, cost);
            pst.setString(4, quant);
            pst.setString(5, bar);
            pst.setString(6, status);
            pst.setInt(7, d);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Succesfully Updated");
            table_update();
            jProd.setText("");
            jDescription.setText("");
            jcost.setText("");
            jquant.setText("");
            jbarcode.setText("");
            jstat.setSelectedIndex(-1);
            jProd1.requestFocus();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

//        String prod = jProd.getText();
//        String prod1 = jProd1.getText();
//        String descript = jDescription.getText();
//        String cost = jcost.getText();
//        String quant = jquant.getText();
//        String bar = jbarcode.getText();
//        String status = jstat.getSelectedItem().toString();
//
//        if (prod.equals("")) {
//            JOptionPane.showMessageDialog(null, "Add A Product Category");
//        } 
//        else if (checkProdId(prod)) {
//            JOptionPane.showMessageDialog(null, "Please add another Product Id in updating");
//        } 
//        else if (descript.equals("")) {
//            JOptionPane.showMessageDialog(null, "Add A Product Description");
//        } else if (cost.equals("")) {
//            JOptionPane.showMessageDialog(null, "Add A Product Cost");
//        } else if (quant.equals("")) {
//            JOptionPane.showMessageDialog(null, "Add A Product Quantity");
//        } else if (bar.equals("")) {
//            JOptionPane.showMessageDialog(null, "Add A Product Barcode");
//        } else if (status.equals("Active")) {
//            JOptionPane.showMessageDialog(null, "Reminder: You are adding an Active Category");
//
//            PreparedStatement ps;
//            String query = "UPDATE `products`  SET `Product` =? ,`Description` =? ,`Cost Price` =? , `Quantity` =? ,`Barcode` =?, `Status` =? ) WHERE `Product_Id` =?";
//            try {
//                ps = connect.getConnection().prepareStatement(query);
//
//               ps.setString(1, prod);
//                ps.setString(2, descript);
//                ps.setString(3, cost);
//                ps.setString(4, quant);
//                ps.setString(5, bar);
//                ps.setString(6, status);
//
//                if (ps.executeUpdate() > 0) {
//                    JOptionPane.showMessageDialog(null, "Successfully Updated");
//                    table_update();
//                }
//
//            } catch (SQLException ex) {
//                System.out.print("Error : " + ex.getMessage());
//            }
//        } else if (!status.equals("Active")) {
//            JOptionPane.showMessageDialog(null, "Reminder: You are adding a DeActive Category");
//            PreparedStatement ps;
//            String query = "UPDATE `products`  SET `Product` =? ,`Description` =? ,`Cost Price` =? , `Quantity` =? ,`Barcode` =?, `Status` =? ) WHERE `Product_Id` =? ";
//            try {
//                ps = connect.getConnection().prepareStatement(query);
//
//               ps.setString(1, prod);
//                ps.setString(2, descript);
//                ps.setString(3, cost);
//                ps.setString(4, quant);
//                ps.setString(5, bar);
//                ps.setString(6, status);
//                if (ps.executeUpdate() > 0) {
//                    JOptionPane.showMessageDialog(null, "Successfully Updated");
//                    table_update();
//                }
//
//            } catch (SQLException ex) {
//                System.out.print("Error : " + ex.getMessage());
//            }
//        } else {
//            PreparedStatement ps;
//            String query = "UPDATE `products`  SET  `Product` =? ,`Description` =? ,`Cost Price` =? , `Quantity` =? ,`Barcode` =?, `Status` =? ) WHERE `Product_Id` =?";
//            try {
//                ps = connect.getConnection().prepareStatement(query);
//
//                ps.setString(1, prod);
//                ps.setString(2, descript);
//                ps.setString(3, cost);
//                ps.setString(4, quant);
//                ps.setString(5, bar);
//                ps.setString(6, status);
//
//                if (ps.executeUpdate() > 0) {
//                    JOptionPane.showMessageDialog(null, "New Product Added");
//                    table_update();
//                }
//
//            } catch (SQLException ex) {
//            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            }
//        }

    }//GEN-LAST:event_jupdateActionPerformed

    private void jdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdelActionPerformed

        DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();
//    
        int selectIndex = jTable1.getSelectedRow();

        int d = Integer.parseInt(model2.getValueAt(selectIndex, 0).toString());

        int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete the Record? ", "Warning", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                PreparedStatement ps;
                String sql;
                sql = "DELETE FROM `products` WHERE `Product_Id`=?";

                con = DriverManager.getConnection("jdbc:mysql://localhost/super mall", "root", "");
                ps = con.prepareStatement(sql);

                ps.setString(1, jProd1.getText());
                jProd1.setText("");
                jProd.setText("");
                jDescription.setText("");
                jcost.setText("");
                jquant.setText("");
                jbarcode.setText("");

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Successfully Deleted!");

            } catch (SQLException ex) {
                Logger.getLogger(Category_1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jdelActionPerformed

    private void jadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadd1ActionPerformed
        String sql = "SELECT * FROM products";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
            }
        } catch (Exception ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_jadd1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
        try {
            int selectIndex = jTable1.getSelectedRow();
            String prod = jProd1.getText();
            String prod1 = jProd.getText();
            String descript = jDescription.getText();
            String cost = jcost.getText();
            String quant = jquant.getText();
            String bar = jbarcode.getText();
            String status = jstat.getSelectedItem().toString();

            jProd1.setText(model1.getValueAt(selectIndex, 0).toString());
            jProd.setText(model1.getValueAt(selectIndex, 1).toString());
            jDescription.setText(model1.getValueAt(selectIndex, 2).toString());
            jcost.setText(model1.getValueAt(selectIndex, 3).toString());
            jquant.setText(model1.getValueAt(selectIndex, 4).toString());
            jbarcode.setText(model1.getValueAt(selectIndex, 5).toString());
            jstat.setSelectedItem(model1.getValueAt(selectIndex, 6).toString());
        } catch (ArrayIndexOutOfBoundsException ar) {
            System.out.println("Error : " + ar.getMessage());

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jadd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadd2ActionPerformed
        String sql = "SELECT * FROM products";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
            }
        } catch (Exception ex) {
            System.out.println("Error : " + ex.getMessage());
        }
    }//GEN-LAST:event_jadd2ActionPerformed
    public boolean checkProdId(String Product_Id) {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM `products` WHERE `Product_Id` =?";
        try {
            ps = connect.getConnection().prepareStatement(query);
            ps.setString(1, Product_Id);

            rs = ps.executeQuery();

            if (rs.next()) {
                checkUser = true;
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return checkUser;
    }

    public boolean checkBar(String Barcode) {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM `products` WHERE `Barcode` =?";
        try {
            ps = connect.getConnection().prepareStatement(query);
            ps.setString(1, Barcode);

            rs = ps.executeQuery();

            if (rs.next()) {
                checkUser = true;
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return checkUser;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane jDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jProd;
    private javax.swing.JTextField jProd1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jadd;
    private javax.swing.JButton jadd1;
    private javax.swing.JButton jadd2;
    private javax.swing.JTextField jbarcode;
    private javax.swing.JTextField jcost;
    private javax.swing.JButton jdel;
    private javax.swing.JTextField jquant;
    private javax.swing.JComboBox<String> jstat;
    private javax.swing.JButton jupdate;
    // End of variables declaration//GEN-END:variables
}
